# Nicole Nos Villalvazo

# NB! Set your site's url, otherwise nothing will work
url: "https:/NosVillalvazoNicole.github.io"
baseurl: "/"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Nicole Nos Villalvazo"
title: "NIKITO"
description:"Me llamo Nicole, soy una persona responsable y siempre me esfuerzo por hacer sonreír a la gente y que se sientan escuchados. Pasé la mayor parte de mi infancia estudiando danza moderna, así que la dedicación y el trabajo en equipo son mis puntos fuertes."
keywords: "Nos Villalvazo, Nicole, personal."
favicon: "iconsmelody.png"
################
# Header layout#
################
black-favicon: " "
background-img: "fondo.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote:"Un blog y demás"
me-img: "/img/sanrio.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

#######
# Blog #
########

post-preview-words: "Avanzamos tan rápido que olvidamos disfrutar el recorrido y al llegar a uno de nuestros muchos destinos queremos volver un momento" 
paginate: 5 
email-share: "nvillalvazo97@gmail.com"

disqus-shortname: "Nicole Nos"

############
# Timeline #
############

events:
  - image: "/.png"
    date: "Agosto 11, 2025"
    description: "Primer día de universidad"
  - image: "//.jpg"
    date: "Junio 16, 2025"
    description: "Día de gradución"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email:"nvillalvazo97@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "/img/huevitoconfresa.png"
author_blurb:"Es un espacio creado por mí para hablar, idear y conforme la marcha lo descubriremos"

##################
# Social Buttons #
##################

social:
  - icon: "Github"
    url: "https://github.com/NosVillalvazoNicole"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about me"
  "Tengo 18 años, cada 19 de julio celebró mi día especial, actualmente estudió la Licenciatura de Negocios Internacionales"
  "Espero seguir aprendiendo de Inglés y mejorar mi pronunciación y lograr aprender portugués, es una lengua que me gusta mucho"
  Blog: "latest-post"
  
  Contact: "9981929944"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
