# Nicole Nos Villalvazo

# NB! Set your site's url, otherwise nothing will work
url: "https:/NosVillalvazoNicole.github.io"
baseurl: "/"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Nicole Nos Villalvazo"
title: "{NIKITO}"
description: "me llamo Nicole, soy una persona responsable y siempre me esfuerzo por hacer sonreír a la gente y que se sientan escuchados. Pasé la mayor parte de mi infancia estudiando danza moderna, así que la dedicación y el trabajo en equipo son mis puntos fuertes."
keywords: "Nos Villalvazo, Nicole, personal."
favicon: "iconsmelody.png"
################
# Header layout#
################
black-favicon: "910856.png"
background-img: "fondo.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "is it better to speak or to die?"
me-img: "/img/jetpacktocat.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

#######
# Blog #
########

post-preview-words: 55
paginate: 5 
email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: false
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false

disqus-shortname: "personal and easy"

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "Agosto 11, 2025"
    description: "Primer día de universidad"
  - image: "/img/timeline/baracktocat.jpg"
    date: "Junio 16, 2025"
    description: "Día de gradución"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "nvillalvazo97@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "/img/author.png"
author_blurb:
  "'Github''s Octocat was designed by Simon Oxley, alongside the white bird Twitter
  used (before they received a proper logo) as part of a usual routine of cranking
  out images for iStock. GitHub saw it, and wanted it, presumably under the notion
  that it can represent how complex code combines to create peculiar things, much
  like the octopuss... except the CEO of GitHub called it an octocat, and it has
  been the octocat since then."

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/le4ker/personal-jekyll-theme"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com"
  - icon: "x-twitter"
    url: "https://twitter.com/"
  - icon: "rss"
    url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
